spring:
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  client:
    fetch-registry: false #means the server will not attempt to download the registry information from other Eureka peers. A server's job is to hold the registry, not to fetch it from others
    register-with-eureka: false # means the server will not attempt to register itself as a service with the discovery registry. The server is the registry; it doesn't need to register with itself.
      # REMARQUE : By default , eureka server always look for another eureka server(and this thing rause an error cause there is no other eureka servers now), but in this case we're working with a standalone eureka server. so in the server-url, we define the only adress that exists
    service-url:
      defaultZone: http://localhost:${server.port}/eureka

